/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import lr0.LR0Parser;
import lr1.LR1Parser;
import util.Grammar;
import util.Rule;

/**
 *
 * @author jamshaid
 */
public class OutputWindow extends javax.swing.JFrame {

    public LR0Parser lr0Parser;

    public LR1Parser lr1Parser;

    /**
     * Creates new form OutputWindow
     * @param parserKind
     * @param lr0Parser
     * @param lR1Parser
     */
    public OutputWindow(String parserKind, LR0Parser lr0Parser,LR1Parser lr1Parser ) {
        this.parserKind=parserKind;
        this.lr0Parser=lr0Parser;
        this.lr1Parser=lr1Parser;
        initComponents();

//        result.setVisible(false);
        /*        if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
            output.setText(GrammarInputController.lr0Parser.getGrammar() + "");
        } else {
            output.setText(GrammarInputController.lr1Parser.getGrammar() + "");
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        augmented_grammar_panel = new javax.swing.JPanel();
        result_scroll_panel = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        first_panel = new javax.swing.JPanel();
        result_scroll_panel1 = new javax.swing.JScrollPane();
        output1 = new javax.swing.JTextArea();
        follow_set_panel = new javax.swing.JPanel();
        result_scroll_panel2 = new javax.swing.JScrollPane();
        output2 = new javax.swing.JTextArea();
        cannonical_panel = new javax.swing.JPanel();
        result_scroll_panel3 = new javax.swing.JScrollPane();
        output3 = new javax.swing.JTextArea();
        goto_panel = new javax.swing.JPanel();
        result_scroll_panel4 = new javax.swing.JScrollPane();
        output4 = new javax.swing.JTextArea();
        action_table_panel = new javax.swing.JPanel();
        result_scroll_panel5 = new javax.swing.JScrollPane();
        output5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        augmented_grammar_panel.setBackground(new java.awt.Color(255, 255, 255));

        output.setColumns(20);
        output.setRows(5);
        output.setText("\n");
        result_scroll_panel.setViewportView(output);

        javax.swing.GroupLayout augmented_grammar_panelLayout = new javax.swing.GroupLayout(augmented_grammar_panel);
        augmented_grammar_panel.setLayout(augmented_grammar_panelLayout);
        augmented_grammar_panelLayout.setHorizontalGroup(
            augmented_grammar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(augmented_grammar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        augmented_grammar_panelLayout.setVerticalGroup(
            augmented_grammar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, augmented_grammar_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Augmented Grammar", augmented_grammar_panel);

        output1.setColumns(20);
        output1.setRows(5);
        result_scroll_panel1.setViewportView(output1);

        javax.swing.GroupLayout first_panelLayout = new javax.swing.GroupLayout(first_panel);
        first_panel.setLayout(first_panelLayout);
        first_panelLayout.setHorizontalGroup(
            first_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(first_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        first_panelLayout.setVerticalGroup(
            first_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, first_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("First Set", first_panel);

        output2.setColumns(20);
        output2.setRows(5);
        result_scroll_panel2.setViewportView(output2);

        javax.swing.GroupLayout follow_set_panelLayout = new javax.swing.GroupLayout(follow_set_panel);
        follow_set_panel.setLayout(follow_set_panelLayout);
        follow_set_panelLayout.setHorizontalGroup(
            follow_set_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(follow_set_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        follow_set_panelLayout.setVerticalGroup(
            follow_set_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, follow_set_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Follow Set", follow_set_panel);

        output3.setColumns(20);
        output3.setRows(5);
        result_scroll_panel3.setViewportView(output3);

        javax.swing.GroupLayout cannonical_panelLayout = new javax.swing.GroupLayout(cannonical_panel);
        cannonical_panel.setLayout(cannonical_panelLayout);
        cannonical_panelLayout.setHorizontalGroup(
            cannonical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cannonical_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        cannonical_panelLayout.setVerticalGroup(
            cannonical_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cannonical_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cannonical Collection", cannonical_panel);

        output4.setColumns(20);
        output4.setRows(5);
        result_scroll_panel4.setViewportView(output4);

        javax.swing.GroupLayout goto_panelLayout = new javax.swing.GroupLayout(goto_panel);
        goto_panel.setLayout(goto_panelLayout);
        goto_panelLayout.setHorizontalGroup(
            goto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goto_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        goto_panelLayout.setVerticalGroup(
            goto_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goto_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Goto Table", goto_panel);

        output5.setColumns(20);
        output5.setRows(5);
        result_scroll_panel5.setViewportView(output5);

        javax.swing.GroupLayout action_table_panelLayout = new javax.swing.GroupLayout(action_table_panel);
        action_table_panel.setLayout(action_table_panelLayout);
        action_table_panelLayout.setHorizontalGroup(
            action_table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_table_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_scroll_panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        action_table_panelLayout.setVerticalGroup(
            action_table_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action_table_panelLayout.createSequentialGroup()
                .addComponent(result_scroll_panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Action Table", action_table_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        output1.setText("");
        output2.setText("");
        output3.setText("");
        output4.setText("");
        output5.setText("");
                  System.err.println("stry"+parserKind);

        switch (jTabbedPane1.getSelectedIndex()) {

            case 0:
                  System.err.println(jTabbedPane1.getSelectedIndex());
                  if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                      
                    String str = "";
                    for (Rule s : lr0Parser.getGrammar().getRules()) {
                        str += s +"\n";
                    }
                    
                    output.setText(str);
                    System.err.println("str"+str);
                    
                } else {
                    String str = "";
                      for (Rule s : lr1Parser.getGrammar().getRules()) {
                        str += s +"\n";
                      }
                    output.setText(str);
                }

                augmented_grammar_panel.add(result_scroll_panel);
                break;

            case 1:
                if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                    String str = "";
                    for (String s : lr0Parser.getGrammar().getFirstSets().keySet()) {
                        str += s + " : " + lr0Parser.getGrammar().getFirstSets().get(s) + "\n";
                    }

                    output1.append(str);
                    System.err.println(str);

                } else {
                    String str = "";
                    for (String s : lr1Parser.getGrammar().getFirstSets().keySet()) {
                        str += s + " : " + lr1Parser.getGrammar().getFirstSets().get(s) + "\n";
                    }
                    output1.setText(str);
                }

                first_panel.add(result_scroll_panel1);
                break;
            case 2:
                if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                    String str = "";
                    for (String s : lr0Parser.getGrammar().getFallowSets().keySet()) {
                        str += s + " : " + lr0Parser.getGrammar().getFallowSets().get(s) + "\n";
                    }
                    output2.setText(str);
                } else {
                    String str = "";
                    for (String s : lr1Parser.getGrammar().getFallowSets().keySet()) {
                        str += s + " : " + lr1Parser.getGrammar().getFallowSets().get(s) + "\n";
                    }
                    output2.setText(str);
                }
                System.err.println(jTabbedPane1.getSelectedIndex());

                follow_set_panel.add(result_scroll_panel);
                break;
            case 3:
                if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                    output3.setText(lr0Parser.canonicalCollectionStr());
                } else {
                    output3.setText(lr1Parser.canonicalCollectionStr());
                }
                System.err.println(jTabbedPane1.getSelectedIndex());

                cannonical_panel.add(result_scroll_panel);
                break;
            case 4:
                if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                    output4.setText(lr0Parser.goToTableStr());
                } else {
                    output4.setText(lr1Parser.goToTableStr());
                }
                System.err.println(jTabbedPane1.getSelectedIndex());

                goto_panel.add(result_scroll_panel);
                break;
            case 5:
                if (parserKind.equals("LR(0)") || parserKind.equals("SLR(1)")) {
                    output5.setText(lr0Parser.actionTableStr());
                } else {
                    output5.setText(lr1Parser.actionTableStr());
                }
                System.err.println(jTabbedPane1.getSelectedIndex());
                action_table_panel.add(result_scroll_panel);
                break;

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged
    String parserKind;

    public void showOutput() {
            this.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action_table_panel;
    private javax.swing.JPanel augmented_grammar_panel;
    private javax.swing.JPanel cannonical_panel;
    private javax.swing.JPanel first_panel;
    private javax.swing.JPanel follow_set_panel;
    private javax.swing.JPanel goto_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextArea output1;
    private javax.swing.JTextArea output2;
    private javax.swing.JTextArea output3;
    private javax.swing.JTextArea output4;
    private javax.swing.JTextArea output5;
    private javax.swing.JScrollPane result_scroll_panel;
    private javax.swing.JScrollPane result_scroll_panel1;
    private javax.swing.JScrollPane result_scroll_panel2;
    private javax.swing.JScrollPane result_scroll_panel3;
    private javax.swing.JScrollPane result_scroll_panel4;
    private javax.swing.JScrollPane result_scroll_panel5;
    // End of variables declaration//GEN-END:variables
}
